services:
  nginx:
      image: nginx:latest
      container_name: nginx_proxy
      ports:
        - "80:80" # Expose Nginx on port 80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount the Nginx config file
      depends_on:
        - backend
      networks:
      - app-network
      
  backend:
    build: ./backend
    ports:
      - "4000:4000" # Changed backend port to avoid conflict
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: my_database
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:4000 # Update backend URL
    networks:
      - app-network

  postgres:
    build: ./database
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: