import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "TWLG.NET",
  description: "Generated by create next app",
};

export default function RoboticsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
