name: Test sudo in Actions

on:
  workflow_dispatch:

jobs:
  check-sudo:
    runs-on: ubuntu-latest # Or your specific runner type

    steps:
      - name: Test sudo with apt update
        run: |
          sudo ss -tuln | grep 5261
